Request for review
ggotora/smashing-mag-clone pull request #1
Opened 2020-08-04 11:25 UTC by oracleot

The aim of this project was to clone the current [Smashing Magazine](https://www.smashingmagazine.com/) landing page with focus on the UX of the website.

Cloning the website with a focus on UX was done by playing with the different colors on the website with varying degrees of the gray color.

The sections highlighted in this clone are:

- Page navigation
- Featured latest articles
- Latest posts
- Different types of Ads
- Person of the week
- Selected authors
- Smashing Magazine Guides
- Newsletter subscription box
- Footer containing several topics

2020-08-04 14:06 UTC, kitpao requested changes
# 👋 Hello @oracleot and @ggotora 

🌟 Nice work guys, you did well, your code clean and organized. And the fact that your page has the nice hover effects of the original, makes it look professional 🏅 

You are missing some requirements, please, check them below in the inline comments 🔽 

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-08-04 14:06 UTC, kitpao commented on assets/styles.css
> +}
- [x] You have a blank space under articles 1 and 3. Please fix this
![image](https://user-images.githubusercontent.com/53256139/89300548-00e3f300-d62e-11ea-9f22-1b184011792d.png)

2020-08-04 14:06 UTC, kitpao commented on index.html
> +          <p class="days">6 Days To Go</p>
- [x] You are missing a row of articles here
![image](https://user-images.githubusercontent.com/53256139/89301206-ff66fa80-d62e-11ea-9dc7-460c6db2c5dd.png)

2020-08-04 14:06 UTC, kitpao commented on index.html
> +        <p class="ninety-deg">Our Guides</p>
- [ ] You are missing a section here, remember we are doing a visual heatmap and this missing section takes almost all the user's attention at that part
![image](https://user-images.githubusercontent.com/53256139/89302032-f7f42100-d62f-11ea-86d8-071322f8d09c.png)

2020-08-04 14:06 UTC, kitpao commented on index.html
> +        </section>
- [x] Here your layout varies, in 1440px screen as required, the original only has 2 articles per row
![image](https://user-images.githubusercontent.com/53256139/89302547-96808200-d630-11ea-96f1-70ac15b3f35a.png)

![image](https://user-images.githubusercontent.com/53256139/89302508-88cafc80-d630-11ea-9c2c-8f0f71fec46d.png)

2020-08-04 14:06 UTC, kitpao commented on index.html
> +            /></a>
- [ ] For good coding practices, avoid using inline styling in your HTML, please add your styles in your CSS file

2020-08-05 12:02 UTC, kitpao requested changes
# 👋 Hi again @oracleot and @ggotora 

⭐ You did a great job fixing the required issues 👏 

✏️ Please note that you missed only one requirement since it is part of the layout
- [ ] Missing design system section:
![image](https://user-images.githubusercontent.com/53256139/89410452-5df0af00-d6e9-11ea-8979-01684790345a.png)

### ♻️ Status: Your project requires 1 additional change ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-08-05 12:22 UTC, oracleot commented
@kitpao kindly check well, we have the section already
![Screenshot 2020-08-05 at 1 18 39 PM](https://user-images.githubusercontent.com/5197661/89412149-79c27800-d71e-11ea-8651-e73a8c0511dc.png)

2020-08-05 13:00 UTC, kitpao approved these changes
# 👋 Hi,

This is the strangest thing ever, I checked your project on Chrome and it is not displaying, changed to Firefox and it is there.
[Here is a recording of the screen](http://youtu.be/S-tPpjyBywA?hd=1)

Here is Chrome's screenshot, I can see the code, but it is not displaying
![image](https://user-images.githubusercontent.com/53256139/89414507-1f122780-d6f0-11ea-9795-5abb357bff0f.png)

Since this is a browser issue, you don't have to worry,
You have complied with all required changes

### 👏 Your project has been approved 👏
### 🚀 You may merge to master and submit the project completition form 🚀

___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-08-05 15:22 UTC, merged